version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  apt_packages:
    - doxygen
    - graphviz
  jobs:
    pre_build:
      - export PBPT_DOCS_EN_LINK="/${READTHEDOCS_LANGUAGE}/${READTHEDOCS_VERSION}/"
      - export PBPT_DOCS_ZH_LINK="/${READTHEDOCS_LANGUAGE}/${READTHEDOCS_VERSION}/zh/"

      - mkdir -p docs/api/doxygen
      - doxygen Doxyfile.in

mkdocs:
  configuration: mkdocs.yml

python:
  install:
    - requirements: docs/requirements.txt
