#pragma once

// Auto-generated file - includes all headers in math/special
// Generated by generate_pbpt_header.py

#include "pbpt/math/special/octahedral.hpp"
#include "pbpt/math/special/polynomial.hpp"
