#pragma once

// Auto-generated file - includes all headers in serde/value/impl
// Generated by generate_pbpt_header.py

#include "pbpt/serde/value/impl/microfacet_model.hpp"
#include "pbpt/serde/value/impl/piecewise_spectrum.hpp"
#include "pbpt/serde/value/impl/render_transform.hpp"
#include "pbpt/serde/value/impl/rgb.hpp"
#include "pbpt/serde/value/impl/transform.hpp"
#include "pbpt/serde/value/impl/wrap_mode.hpp"
