/**
 * @file
 * @brief Convenience umbrella header including all geometry components.
 *
 * This header is auto-generated by `generate_pbpt_header.py` and simply
 * re-exports the main geometry types and utilities (rays, bounds, frames,
 * transforms, spherical helpers, etc.).
 */
#pragma once

// Auto-generated file - includes all headers in geometry
// Generated by generate_pbpt_header.py

#include "bounds.hpp"
#include "directional_cone.hpp"
#include "frame.hpp"
#include "interaction.hpp"
#include "ray.hpp"
#include "spherical.hpp"
#include "transform.hpp"
