#pragma once

// Auto-generated file - includes all headers in camera/plugin/camera
// Generated by generate_pbpt_header.py

#include "pbpt/camera/plugin/camera/camera_type.hpp"
#include "pbpt/camera/plugin/camera/projective_cameras.hpp"
#include "pbpt/camera/plugin/camera/spherical_camera.hpp"
