#pragma once

// Auto-generated file - includes all headers in serde/domain
// Generated by generate_pbpt_header.py

#include "pbpt/serde/domain/trait_contracts.hpp"
#include "pbpt/serde/domain/typelist.hpp"
