/**
 * @file
 * @brief Aggregate header that includes all math components.
 */
#pragma once

// Auto-generated file - includes all headers in math
// Generated by generate_pbpt_header.py

#include "format.hpp"
#include "compat.hpp"
#include "function.hpp"
#include "homogeneous.hpp"
#include "matrix.hpp"
#include "normal.hpp"
#include "octahedral.hpp"
#include "operator.hpp"
#include "point.hpp"
#include "polynomial.hpp"
#include "quaternion.hpp"
#include "random_generator.hpp"
#include "tuple.hpp"
#include "type_alias.hpp"
#include "utils.hpp"
#include "vector.hpp"
