#pragma once

// Auto-generated file - includes all headers in math
// Generated by generate_pbpt_header.py

#include "pbpt/math/basic/algebra_concepts.hpp"
#include "pbpt/math/basic/comparison.hpp"
#include "pbpt/math/basic/format.hpp"
#include "pbpt/math/basic/function.hpp"
#include "pbpt/math/basic/random_generator.hpp"
#include "pbpt/math/basic/rebind.hpp"
#include "pbpt/math/basic/type_alias.hpp"
#include "pbpt/math/basic/utils.hpp"
#include "pbpt/math/complex/complex.hpp"
#include "pbpt/math/complex/quaternion.hpp"
#include "pbpt/math/matrix/matrix.hpp"
#include "pbpt/math/matrix/matrix_views.hpp"
#include "pbpt/math/spatial/normal.hpp"
#include "pbpt/math/spatial/point.hpp"
#include "pbpt/math/spatial/tuple.hpp"
#include "pbpt/math/spatial/vector.hpp"
#include "pbpt/math/special/octahedral.hpp"
#include "pbpt/math/special/polynomial.hpp"
