/**
 * @file
 * @brief Convenience umbrella header including all radiometry components.
 *
 * This header is auto-generated by `generate_pbpt_header.py` and re-exports
 * the main radiometric types and utilities (spectra, color spaces, units,
 * sampling, and standard spectra).
 */
#pragma once

// Auto-generated file - includes all headers in radiometry
// Generated by generate_pbpt_header.py

#include "color.hpp"
#include "color_space.hpp"
#include "color_spectrum_optimizer.hpp"
#include "radiometric_integrals.hpp"
#include "sampled_spectrum.hpp"
#include "spectrum_distribution.hpp"
#include "spectrum_loader.hpp"

#include "constant/swatch_reflectances_spectrum.hpp"
#include "constant/xyz_spectrum.hpp"
#include "constant/illuminant_spectrum.hpp"
#include "constant/standard_color_spaces.hpp"
