#pragma once

// Auto-generated file - includes all headers in serde
// Generated by generate_pbpt_header.py

#include "pbpt/serde/context.hpp"
#include "pbpt/serde/dispatch.hpp"
#include "pbpt/serde/mi3_schema_guard.hpp"
#include "pbpt/serde/scene_io_config.hpp"
#include "pbpt/serde/scene_loader.hpp"
#include "pbpt/serde/scene_writer.hpp"
#include "pbpt/serde/xml_result.hpp"
