#pragma once

// Auto-generated file - includes all headers in light_sampler
// Generated by generate_pbpt_header.py

#include "pbpt/light_sampler/concepts.hpp"
#include "pbpt/light_sampler/light_sampler.hpp"
