#pragma once

// Auto-generated file - includes all headers in camera/plugin/film
// Generated by generate_pbpt_header.py

#include "pbpt/camera/plugin/film/film_type.hpp"
#include "pbpt/camera/plugin/film/hdr_film.hpp"
