#pragma once

// Auto-generated file - includes all headers in camera
// Generated by generate_pbpt_header.py

#include "pbpt/camera/camera.hpp"
#include "pbpt/camera/concepts.hpp"
#include "pbpt/camera/film.hpp"
#include "pbpt/camera/fov_axis.hpp"
#include "pbpt/camera/pixel_filter.hpp"
#include "pbpt/camera/pixel_sensor.hpp"
#include "pbpt/camera/render_transform.hpp"
