#pragma once

// Auto-generated file - includes all headers in math/complex
// Generated by generate_pbpt_header.py

#include "pbpt/math/complex/complex.hpp"
#include "pbpt/math/complex/quaternion.hpp"
