#pragma once

// Auto-generated file - includes all headers in math/basic
// Generated by generate_pbpt_header.py

#include "pbpt/math/basic/algebra_concepts.hpp"
#include "pbpt/math/basic/comparison.hpp"
#include "pbpt/math/basic/format.hpp"
#include "pbpt/math/basic/function.hpp"
#include "pbpt/math/basic/random_generator.hpp"
#include "pbpt/math/basic/rebind.hpp"
#include "pbpt/math/basic/type_alias.hpp"
#include "pbpt/math/basic/utils.hpp"
