#pragma once

// Auto-generated file - includes all headers in camera
// Generated by generate_pbpt_header.py

#include "camera.hpp"
#include "projective_camera.hpp"
#include "film.hpp"
#include "render_transform.hpp"