#pragma once

// Auto-generated file - includes all headers in camera
// Generated by generate_pbpt_header.py

#include "camera.hpp"
#include "render_transform.hpp"
#include "film.hpp"
#include "camera_projection.hpp"
#include "camera_sample.hpp"
