/**
 * @file
 * @brief Convenience umbrella header including all camera components.
 *
 * This header is auto-generated by `generate_pbpt_header.py` and simply
 * re-exports the main camera-related interfaces (camera models, film,
 * pixel sensor, projections, and render transforms).
 */
#pragma once

#include "pbpt/camera/camera.hpp"
#include "pbpt/camera/plugin/camera/projective_cameras.hpp"
#include "pbpt/camera/plugin/camera/spherical_camera.hpp"
#include "pbpt/camera/film.hpp"
#include "pbpt/camera/plugin/film/hdr_film.hpp"
#include "pbpt/camera/pixel_sensor.hpp"
#include "pbpt/camera/render_transform.hpp"
#include "pbpt/camera/pixel_filter.hpp"
#include "pbpt/camera/plugin/pixel_filter/box_filter.hpp"
#include "pbpt/camera/plugin/pixel_filter/gaussian_filter.hpp"
#include "pbpt/camera/plugin/pixel_filter/tent_filter.hpp"
