#pragma once

// Auto-generated file - includes all headers in aggregate/plugin/aggregate
// Generated by generate_pbpt_header.py

#include "pbpt/aggregate/plugin/aggregate/aggregate_type.hpp"
#include "pbpt/aggregate/plugin/aggregate/embree_aggregate.hpp"
#include "pbpt/aggregate/plugin/aggregate/linear_aggregate.hpp"
