#pragma once

// Auto-generated file - includes all headers in geometry
// Generated by generate_pbpt_header.py

#include "pbpt/geometry/bounds.hpp"
#include "pbpt/geometry/directional_cone.hpp"
#include "pbpt/geometry/frame.hpp"
#include "pbpt/geometry/interaction.hpp"
#include "pbpt/geometry/ray.hpp"
#include "pbpt/geometry/spherical.hpp"
#include "pbpt/geometry/transform.hpp"
