#pragma once

// Auto-generated file - includes all headers in sampler
// Generated by generate_pbpt_header.py

#include "pbpt/sampler/1d.hpp"
#include "pbpt/sampler/2d.hpp"
#include "pbpt/sampler/3d.hpp"
#include "pbpt/sampler/discrete.hpp"
#include "pbpt/sampler/utils.hpp"
