#!/usr/bin/env python3
"""Convert PBRT rgb2spec output into a PBPT-friendly C++ translation unit."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys
from textwrap import dedent


def _rewrite_namespace(text: str, namespace: str) -> str:
    """Rewrite the PBRT namespace to the requested one."""
    src_ns = "namespace pbrt {"
    dst_ns = f"namespace {namespace} {{"
    if src_ns not in text:
        raise RuntimeError("Input file does not contain the expected 'namespace pbrt {' marker.")
    text = text.replace(src_ns, dst_ns, 1)
    text = text.replace("} // namespace pbrt", f"}} // namespace {namespace}")
    return text


def _strip_extern(text: str) -> str:
    """Definitions already provide storage, no need to keep 'extern'."""
    return text.replace("extern const", "const")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input",
        required=True,
        type=Path,
        help="Path to PBRT rgb2spec output (rgbspectrum_*.cpp).",
    )
    parser.add_argument(
        "--output",
        required=True,
        type=Path,
        help="Destination file for the rewritten translation unit.",
    )
    parser.add_argument(
        "--namespace",
        default="pbpt::radiometry",
        help="Namespace to wrap generated symbols into.",
    )
    args = parser.parse_args(argv)

    if not args.input.exists():
        raise SystemExit(f"Input file not found: {args.input}")

    text = args.input.read_text(encoding="utf-8")
    text = _rewrite_namespace(text, args.namespace)
    text = _strip_extern(text)

    header = dedent(
        f"""\
        // Auto-generated by script/generate_rgb_spectrum_lut.py
        // Source: {args.input}
        // Data originates from PBRT's rgb2spec optimization (Apache-2.0).

        #include "pbpt/radiometry/color_spectrum_lut.hpp"

        """
    )

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(header + text, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
