#pragma once

// Auto-generated file - includes all headers in material/plugin/material
// Generated by generate_pbpt_header.py

#include "pbpt/material/plugin/material/conductor_material.hpp"
#include "pbpt/material/plugin/material/conductor_rough_material.hpp"
#include "pbpt/material/plugin/material/conductor_specular_material.hpp"
#include "pbpt/material/plugin/material/dielectric_material.hpp"
#include "pbpt/material/plugin/material/dielectric_rough_material.hpp"
#include "pbpt/material/plugin/material/dielectric_specular_material.hpp"
#include "pbpt/material/plugin/material/lambertian_material.hpp"
#include "pbpt/material/plugin/material/material_type.hpp"
