#pragma once

// Auto-generated file - includes all headers in math/spatial
// Generated by generate_pbpt_header.py

#include "pbpt/math/spatial/normal.hpp"
#include "pbpt/math/spatial/point.hpp"
#include "pbpt/math/spatial/tuple.hpp"
#include "pbpt/math/spatial/vector.hpp"
