#pragma once

// Auto-generated file - includes all headers in radiometry
// Generated by generate_pbpt_header.py

#include "pbpt/radiometry/color.hpp"
#include "pbpt/radiometry/color_space.hpp"
#include "pbpt/radiometry/color_spectrum_lut.hpp"
#include "pbpt/radiometry/color_spectrum_optimizer.hpp"
#include "pbpt/radiometry/sampled_spectrum.hpp"
#include "pbpt/radiometry/spectrum_distribution.hpp"
#include "pbpt/radiometry/spectrum_loader.hpp"
