#pragma once

// Auto-generated file - includes all headers in radiometry/constant
// Generated by generate_pbpt_header.py

#include "pbpt/radiometry/constant/illuminant_spectrum.hpp"
#include "pbpt/radiometry/constant/lambda.hpp"
#include "pbpt/radiometry/constant/metal_ior_spectrum.hpp"
#include "pbpt/radiometry/constant/standard_color_spaces.hpp"
#include "pbpt/radiometry/constant/swatch_reflectances_spectrum.hpp"
#include "pbpt/radiometry/constant/xyz_spectrum.hpp"
