#pragma once

// Auto-generated file - includes all headers in light_sampler/plugin/light_sampler
// Generated by generate_pbpt_header.py

#include "pbpt/light_sampler/plugin/light_sampler/light_sampler_type.hpp"
#include "pbpt/light_sampler/plugin/light_sampler/uniform_light_sampler.hpp"
