#pragma once

// Auto-generated file - includes all headers in camera/plugin/pixel_filter
// Generated by generate_pbpt_header.py

#include "pbpt/camera/plugin/pixel_filter/box_filter.hpp"
#include "pbpt/camera/plugin/pixel_filter/gaussian_filter.hpp"
#include "pbpt/camera/plugin/pixel_filter/pixel_filter_type.hpp"
#include "pbpt/camera/plugin/pixel_filter/tent_filter.hpp"
