#pragma once

// Auto-generated file - includes all headers in light/plugin/light
// Generated by generate_pbpt_header.py

#include "pbpt/light/plugin/light/area_light.hpp"
#include "pbpt/light/plugin/light/light_type.hpp"
