#pragma once

// Auto-generated file - includes all headers in shape/plugin/shape
// Generated by generate_pbpt_header.py

#include "pbpt/shape/plugin/shape/shape_type.hpp"
#include "pbpt/shape/plugin/shape/sphere.hpp"
#include "pbpt/shape/plugin/shape/triangle.hpp"
