#pragma once

// Auto-generated file - includes all headers in material/plugin/bxdf
// Generated by generate_pbpt_header.py

#include "pbpt/material/plugin/bxdf/bxdf_type.hpp"
#include "pbpt/material/plugin/bxdf/conductor_bxdf.hpp"
#include "pbpt/material/plugin/bxdf/conductor_rough_bxdf.hpp"
#include "pbpt/material/plugin/bxdf/conductor_specular_bxdf.hpp"
#include "pbpt/material/plugin/bxdf/dielectric_bxdf.hpp"
#include "pbpt/material/plugin/bxdf/dielectric_rough_bxdf.hpp"
#include "pbpt/material/plugin/bxdf/dielectric_specular_bxdf.hpp"
#include "pbpt/material/plugin/bxdf/lambertian_bxdf.hpp"
#include "pbpt/material/plugin/bxdf/null_bxdf.hpp"
