#pragma once

// Auto-generated file - includes all headers in material
// Generated by generate_pbpt_header.py

#include "pbpt/material/bsdf.hpp"
#include "pbpt/material/bxdf.hpp"
#include "pbpt/material/material.hpp"
#include "pbpt/material/model.hpp"
#include "pbpt/material/optics.hpp"
