#pragma once

// Auto-generated file - includes all headers in texture/plugin/texture
// Generated by generate_pbpt_header.py

#include "pbpt/texture/plugin/texture/bitmap_texture.hpp"
#include "pbpt/texture/plugin/texture/checkerboard_texture.hpp"
#include "pbpt/texture/plugin/texture/constant_texture.hpp"
#include "pbpt/texture/plugin/texture/rsp_spectrum_texture.hpp"
#include "pbpt/texture/plugin/texture/texture_type.hpp"
