# find and configure third-party libraries
if(PBPT_BUILD_TESTS)
  find_package(GTest CONFIG REQUIRED)
  message(STATUS "PBPT_BUILD_TESTS is ON; GoogleTest will be configured for tests.")
else()
  message(STATUS "PBPT_BUILD_TESTS is OFF; GoogleTest will NOT be configured.")
endif()

find_package(stb            CONFIG REQUIRED)
find_package(OpenEXR       CONFIG REQUIRED)
find_package(pugixml        CONFIG REQUIRED)
find_package(embree         CONFIG REQUIRED)
find_package(TBB            CONFIG REQUIRED)

# build stb implementation
set(STB_GENERATED_DIR "${CMAKE_BINARY_DIR}/generated")
set(STB_IMPLEMENTATION_FILE "${STB_GENERATED_DIR}/stb.cpp")
file(MAKE_DIRECTORY ${STB_GENERATED_DIR})
set(STB_IMPLEMENTATION_CONTENT
"// Auto-generated STB implementation file
// This file is automatically generated by CMake

#define STB_IMAGE_IMPLEMENTATION
#include \"stb_image.h\"

#define STB_IMAGE_WRITE_IMPLEMENTATION
#include \"stb_image_write.h\"

#define STB_TRUETYPE_IMPLEMENTATION
#include \"stb_truetype.h\"
")
file(WRITE "${STB_IMPLEMENTATION_FILE}" "${STB_IMPLEMENTATION_CONTENT}")
message(STATUS "STB implementation file generated at: ${STB_IMPLEMENTATION_FILE}")

add_library(pbpt_stb_impl STATIC "${STB_IMPLEMENTATION_FILE}")
target_link_libraries(pbpt_stb_impl PUBLIC stb::stb)
