#pragma once

// Auto-generated file - includes all headers in integrator/plugin/integrator
// Generated by generate_pbpt_header.py

#include "pbpt/integrator/plugin/integrator/integrator_type.hpp"
#include "pbpt/integrator/plugin/integrator/path_integrator.hpp"
#include "pbpt/integrator/plugin/integrator/simple_path_integrator.hpp"
