#pragma once

// Auto-generated file - includes all headers in serde/domain/impl
// Generated by generate_pbpt_header.py

#include "pbpt/serde/domain/impl/camera.hpp"
#include "pbpt/serde/domain/impl/integrator.hpp"
#include "pbpt/serde/domain/impl/light_sampler.hpp"
#include "pbpt/serde/domain/impl/material.hpp"
#include "pbpt/serde/domain/impl/sampler.hpp"
#include "pbpt/serde/domain/impl/shape.hpp"
#include "pbpt/serde/domain/impl/texture.hpp"
