# .github/workflows/ci.yml

# 工作流的名称
name: C++ CI/CD

# 触发工作流的事件
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup headless display
      uses: pyvista/setup-headless-display-action@v3

    - name: Prepare Vulkan SDK
      uses: humbletim/setup-vulkan-sdk@v1.2.1
      with:
        vulkan-query-version: 1.4.304.0
        vulkan-components: Vulkan-Headers, Vulkan-Loader
        vulkan-use-cache: true

    - name: Configure CMake (Vulkan)
      run: cmake -S . -B build -DPBPT_BUILD_TESTS=ON -DRENDER_BACKEND=Vulkan

    - name: Build (Vulkan)
      run: cmake --build build --config Release

    - name: Test (Vulkan)
      run: ctest --test-dir build -C Release --output-on-failure

    - name: Configure CMake (OpenGL)
      run: cmake -S . -B build -DPBPT_BUILD_TESTS=ON -DRENDER_BACKEND=OpenGL

    - name: Build (OpenGL)
      run: cmake --build build --config Release

    - name: Test (OpenGL)
      run: ctest --test-dir build -C Release --output-on-failure
